WARNING 2019-06-18 03:42:15,515 base 152 Not Found: /
WARNING 2019-06-18 03:42:15,518 basehttp 124 "GET / HTTP/1.1" 404 2110
WARNING 2019-06-18 03:42:16,641 base 152 Not Found: /favicon.ico
WARNING 2019-06-18 03:42:16,642 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2161
WARNING 2019-06-18 03:42:32,997 base 152 Not Found: /image_codes/11/
WARNING 2019-06-18 03:42:32,998 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 404 2173
WARNING 2019-06-18 03:47:08,995 base 152 Not Found: /
WARNING 2019-06-18 03:47:08,996 basehttp 124 "GET / HTTP/1.1" 404 2109
WARNING 2019-06-18 03:57:21,235 base 152 Not Found: /
WARNING 2019-06-18 03:57:21,236 basehttp 124 "GET / HTTP/1.1" 404 2109
WARNING 2019-06-18 03:57:43,096 base 152 Not Found: /users/login
WARNING 2019-06-18 03:57:43,097 basehttp 124 "GET /users/login HTTP/1.1" 404 2160
WARNING 2019-06-18 08:57:26,238 base 152 Not Found: /image_code/11/
WARNING 2019-06-18 08:57:26,240 basehttp 124 "GET /image_code/11/ HTTP/1.1" 404 2175
WARNING 2019-06-18 08:57:27,303 base 152 Not Found: /favicon.ico
WARNING 2019-06-18 08:57:27,304 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2166
ERROR 2019-06-18 08:58:11,783 exceptions 33 [<verifications.views.ImageCodeView object at 0x10d5d90b8>] Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR 2019-06-18 08:58:11,874 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 507 5310
INFO 2019-06-18 08:58:12,065 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2019-06-18 08:58:12,066 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2019-06-18 08:58:12,066 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
INFO 2019-06-18 08:58:12,069 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2019-06-18 08:58:12,073 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
INFO 2019-06-18 08:58:12,074 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2019-06-18 08:58:12,138 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2019-06-18 08:58:12,156 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2019-06-18 08:58:12,158 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
INFO 2019-06-18 08:58:12,158 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2019-06-18 08:58:12,159 basehttp 124 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
ERROR 2019-06-18 09:44:31,948 exceptions 33 [<verifications.views.ImageCodeView object at 0x10d64f1d0>] Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR 2019-06-18 09:44:31,976 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 507 5310
INFO 2019-06-18 10:05:22,450 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 200 3625
INFO 2019-06-18 10:05:27,543 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 200 3150
INFO 2019-06-18 12:49:59,593 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 200 3253
WARNING 2019-06-18 15:24:38,056 base 152 Not Found: /
WARNING 2019-06-18 15:24:38,060 basehttp 124 "GET / HTTP/1.1" 404 2109
WARNING 2019-06-18 15:24:50,288 base 152 Not Found: /register.html
WARNING 2019-06-18 15:24:50,289 basehttp 124 "GET /register.html HTTP/1.1" 404 2166
WARNING 2019-06-18 15:27:17,831 base 152 Not Found: /register.html
WARNING 2019-06-18 15:27:17,836 basehttp 124 "GET /register.html HTTP/1.1" 404 2166
WARNING 2019-06-18 15:28:50,573 base 152 Not Found: /register.html
WARNING 2019-06-18 15:28:50,573 basehttp 124 "GET /register.html HTTP/1.1" 404 2166
WARNING 2019-06-18 19:05:38,587 base 152 Not Found: /
WARNING 2019-06-18 19:05:38,591 basehttp 124 "GET / HTTP/1.1" 404 2110
WARNING 2019-06-18 19:05:55,010 base 152 Not Found: /rigister.html
WARNING 2019-06-18 19:05:55,011 basehttp 124 "GET /rigister.html HTTP/1.1" 404 2167
WARNING 2019-06-18 19:08:55,957 base 152 Not Found: /register.html
WARNING 2019-06-18 19:08:55,958 basehttp 124 "GET /register.html HTTP/1.1" 404 2166
WARNING 2019-06-18 19:54:10,467 base 152 Not Found: /
WARNING 2019-06-18 19:54:10,504 basehttp 124 "GET / HTTP/1.1" 404 2109
WARNING 2019-06-18 19:54:24,871 base 152 Not Found: /
WARNING 2019-06-18 19:54:24,875 basehttp 124 "GET / HTTP/1.1" 404 2115
INFO 2019-06-18 19:56:08,621 basehttp 124 "GET /image_codes/535c8c3d-8d7b-49e1-ba15-dafce5994587/ HTTP/1.1" 200 3388
WARNING 2019-06-18 19:57:46,140 base 152 Not Found: /
WARNING 2019-06-18 19:57:46,143 basehttp 124 "GET / HTTP/1.1" 404 2115
INFO 2019-06-18 19:58:17,032 basehttp 124 "GET /image_codes/b878894c-c191-4151-97e3-907c1c08709f/ HTTP/1.1" 200 2987
INFO 2019-06-18 19:58:18,808 basehttp 124 "GET /image_codes/e3a7010e-c542-4344-802b-d6feeb175c8c/ HTTP/1.1" 200 3196
INFO 2019-06-18 19:58:19,434 basehttp 124 "GET /image_codes/cba034fc-a79e-495f-8535-72ad48db6a92/ HTTP/1.1" 200 3059
INFO 2019-06-18 19:58:19,907 basehttp 124 "GET /image_codes/b2636053-36b7-446b-8086-105f65a05abf/ HTTP/1.1" 200 3261
INFO 2019-06-18 19:58:20,175 basehttp 124 "GET /image_codes/798703cf-b422-4c0c-8a48-7bea6bed2cce/ HTTP/1.1" 200 2888
INFO 2019-06-18 19:58:20,362 basehttp 124 "GET /image_codes/62f382ac-a1ab-479f-96c9-6ad40acf463d/ HTTP/1.1" 200 3484
INFO 2019-06-18 19:58:20,535 basehttp 124 "GET /image_codes/b13750a1-8db2-4bcd-9be4-d511bbd2851b/ HTTP/1.1" 200 3378
INFO 2019-06-18 19:58:20,746 basehttp 124 "GET /image_codes/6424ded4-3180-425d-866d-68e6bd4d7e61/ HTTP/1.1" 200 2848
INFO 2019-06-18 19:58:20,942 basehttp 124 "GET /image_codes/2a04892e-222c-4d89-93c2-8569a51cb94f/ HTTP/1.1" 200 2657
INFO 2019-06-20 10:18:05,991 basehttp 124 "GET /image_codes/eaacf8b5-cd23-4beb-99ca-d21da9f07207/ HTTP/1.1" 200 2981
INFO 2019-06-20 10:19:16,268 basehttp 124 "GET /image_codes/8dc7ac14-30eb-4e5d-9a8f-d86f9f2d7c63/ HTTP/1.1" 200 3110
INFO 2019-06-20 10:48:12,770 basehttp 124 "GET /image_codes/68ec8cf3-14eb-4f67-9ac6-a94c125e4c19/ HTTP/1.1" 200 3011
INFO 2019-06-20 10:51:55,297 basehttp 124 "GET /image_codes/8eb01501-6ea0-462a-b8eb-f850cd86e3c0/ HTTP/1.1" 200 3381
WARNING 2019-06-20 10:52:05,143 basehttp 124 "GET /sms_codes/15111111111/?text=scxb&image_code_id=8eb01501-6ea0-462a-b8eb-f850cd86e3c0 HTTP/1.1" 400 46
INFO 2019-06-20 15:08:52,158 basehttp 124 "GET /image_codes/92f844e6-37ac-43d1-9d47-2352d982f835/ HTTP/1.1" 200 3131
ERROR 2019-06-20 15:09:13,314 exception 135 Internal Server Error: /sms_codes/15111111111/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 58, in get
    pl = redis_conn.pipline()
AttributeError: 'StrictRedis' object has no attribute 'pipline'
ERROR 2019-06-20 15:09:13,355 basehttp 124 "GET /sms_codes/15111111111/?text=FUVQ&image_code_id=92f844e6-37ac-43d1-9d47-2352d982f835 HTTP/1.1" 500 16322
WARNING 2019-06-20 15:09:17,462 basehttp 124 "GET /sms_codes/15111111111/?text=FUVQ&image_code_id=92f844e6-37ac-43d1-9d47-2352d982f835 HTTP/1.1" 400 46
INFO 2019-06-20 15:09:17,529 basehttp 124 "GET /image_codes/09c30883-ee68-46b3-b961-56a20529b4b4/ HTTP/1.1" 200 3021
ERROR 2019-06-20 15:09:31,714 exception 135 Internal Server Error: /sms_codes/15111111111/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 58, in get
    pl = redis_conn.pipline()
AttributeError: 'StrictRedis' object has no attribute 'pipline'
ERROR 2019-06-20 15:09:31,732 basehttp 124 "GET /sms_codes/15111111111/?text=EZMH&image_code_id=09c30883-ee68-46b3-b961-56a20529b4b4 HTTP/1.1" 500 16322
WARNING 2019-06-20 15:09:32,744 basehttp 124 "GET /sms_codes/15111111111/?text=EZMH&image_code_id=09c30883-ee68-46b3-b961-56a20529b4b4 HTTP/1.1" 400 46
INFO 2019-06-20 15:09:32,774 basehttp 124 "GET /image_codes/b6c57551-501e-4f40-a66f-4caa261150b4/ HTTP/1.1" 200 3434
ERROR 2019-06-20 15:10:36,052 exception 135 Internal Server Error: /sms_codes/15111111111/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 58, in get
    pl = redis_conn.pipline()
AttributeError: 'StrictRedis' object has no attribute 'pipline'
ERROR 2019-06-20 15:10:36,097 basehttp 124 "GET /sms_codes/15111111111/?text=rfap&image_code_id=b6c57551-501e-4f40-a66f-4caa261150b4 HTTP/1.1" 500 16322
WARNING 2019-06-20 15:10:40,003 basehttp 124 "GET /sms_codes/15111111111/?text=rfap&image_code_id=b6c57551-501e-4f40-a66f-4caa261150b4 HTTP/1.1" 400 46
INFO 2019-06-20 15:10:40,065 basehttp 124 "GET /image_codes/f4ffc2f1-abef-46c7-a9bb-bf2231dd8e87/ HTTP/1.1" 200 3777
ERROR 2019-06-20 15:12:53,902 exception 135 Internal Server Error: /sms_codes/15111111111/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 58, in get
    pl = redis_conn.pipline()
AttributeError: 'StrictRedis' object has no attribute 'pipline'
ERROR 2019-06-20 15:12:53,953 basehttp 124 "GET /sms_codes/15111111111/?text=mukg&image_code_id=f4ffc2f1-abef-46c7-a9bb-bf2231dd8e87 HTTP/1.1" 500 16322
INFO 2019-06-20 15:17:55,925 basehttp 124 "GET /image_codes/88e6a75e-5a7f-42c7-81bd-d8e7fb1085e6/ HTTP/1.1" 200 3264
WARNING 2019-06-20 15:18:10,966 views 81 发送验证码短信[失败][ mobile: 15111111111 ]
ERROR 2019-06-20 15:18:10,967 basehttp 124 "GET /sms_codes/15111111111/?text=vase&image_code_id=88e6a75e-5a7f-42c7-81bd-d8e7fb1085e6 HTTP/1.1" 500 20
WARNING 2019-06-20 15:18:13,857 basehttp 124 "GET /sms_codes/15111111111/?text=vase&image_code_id=88e6a75e-5a7f-42c7-81bd-d8e7fb1085e6 HTTP/1.1" 400 46
INFO 2019-06-20 15:18:13,892 basehttp 124 "GET /image_codes/06bbe231-1cae-4208-b196-fe3a41e90ea1/ HTTP/1.1" 200 3056
WARNING 2019-06-20 15:18:22,016 basehttp 124 "GET /sms_codes/15111111111/?text=vgxc&image_code_id=06bbe231-1cae-4208-b196-fe3a41e90ea1 HTTP/1.1" 400 49
INFO 2019-06-20 15:18:22,048 basehttp 124 "GET /image_codes/40c15481-8dc4-4668-a4a9-1ee32001b6e4/ HTTP/1.1" 200 2975
WARNING 2019-06-20 15:19:31,166 views 81 发送验证码短信[失败][ mobile: 15111411041 ]
ERROR 2019-06-20 15:19:31,169 basehttp 124 "GET /sms_codes/15111411041/?text=cxpv&image_code_id=40c15481-8dc4-4668-a4a9-1ee32001b6e4 HTTP/1.1" 500 20
WARNING 2019-06-20 15:24:23,584 basehttp 124 "GET /sms_codes/15111411041/?text=cxpv&image_code_id=40c15481-8dc4-4668-a4a9-1ee32001b6e4 HTTP/1.1" 400 46
INFO 2019-06-20 15:24:23,630 basehttp 124 "GET /image_codes/3c5f15a9-1071-4625-a7ac-536be025eeb1/ HTTP/1.1" 200 3196
WARNING 2019-06-20 15:24:32,855 views 81 发送验证码短信[失败][ mobile: 15111411041 ]
ERROR 2019-06-20 15:24:32,858 basehttp 124 "GET /sms_codes/15111411041/?text=6rus&image_code_id=3c5f15a9-1071-4625-a7ac-536be025eeb1 HTTP/1.1" 500 20
WARNING 2019-06-20 15:24:33,996 basehttp 124 "GET /sms_codes/15111411041/?text=6rus&image_code_id=3c5f15a9-1071-4625-a7ac-536be025eeb1 HTTP/1.1" 400 46
INFO 2019-06-20 15:24:34,027 basehttp 124 "GET /image_codes/f030f05e-5c17-4acc-91cd-3e5ff075cfc7/ HTTP/1.1" 200 3163
INFO 2019-06-20 15:25:25,419 basehttp 124 "GET /image_codes/38052c7b-e610-43ef-ad9b-c2c1810b9e28/ HTTP/1.1" 200 3090
INFO 2019-06-20 15:29:45,835 basehttp 124 "GET /image_codes/f51a4e90-0509-4a94-87d0-64740ade7250/ HTTP/1.1" 200 3158
INFO 2019-06-20 15:29:56,502 basehttp 124 "GET /image_codes/febe3f6f-0f22-4f41-8832-2e226b18eb91/ HTTP/1.1" 200 3438
WARNING 2019-06-20 15:30:04,131 views 81 发送验证码短信[失败][ mobile: 15111411041 ]
ERROR 2019-06-20 15:30:04,133 basehttp 124 "GET /sms_codes/15111411041/?text=cyu6&image_code_id=febe3f6f-0f22-4f41-8832-2e226b18eb91 HTTP/1.1" 500 20
INFO 2019-06-20 23:03:34,917 basehttp 124 "GET /image_codes/3888d341-f0e2-4bad-911f-b22c049a6ffb/ HTTP/1.1" 200 2979
INFO 2019-06-20 23:04:03,653 basehttp 124 "GET /image_codes/f7447e34-e474-4296-9410-e41a94166c3b/ HTTP/1.1" 200 3329
WARNING 2019-06-20 23:04:11,810 base 152 Not Found: /usernames/python1/count/
WARNING 2019-06-20 23:04:11,813 basehttp 124 "GET /usernames/python1/count/ HTTP/1.1" 404 2549
WARNING 2019-06-20 23:04:21,291 base 152 Not Found: /mobiles/15111411041/count/
WARNING 2019-06-20 23:04:21,292 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 404 2555
WARNING 2019-06-20 23:04:27,157 base 152 Not Found: /mobiles/15111411041/count/
WARNING 2019-06-20 23:04:27,160 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 404 2555
ERROR 2019-06-20 23:04:27,373 exception 135 Internal Server Error: /sms_codes/15111411041/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/utils/functional.py", line 42, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 921, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 87, in get
    send_sms_code.delay(mobile, sms_code, expires, constants.SMS_CODE_TEMP_ID)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/celery/app/base.py", line 756, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/connection.py", line 510, in _ensured
    return fun(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/utils/functional.py", line 44, in __call__
    value = self.__value__ = self.__contract__()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/connection.py", line 852, in default_channel
    self.ensure_connection(**conn_opts)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/utils/functional.py", line 343, in retry_over_time
    return fun(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/transport/redis.py", line 496, in __init__
    self.Client = self._get_client()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/kombu/transport/redis.py", line 957, in _get_client
    'You have {0.__version__}'.format(redis))
kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
ERROR 2019-06-20 23:04:27,512 basehttp 124 "GET /sms_codes/15111411041/?text=xeir&image_code_id=f7447e34-e474-4296-9410-e41a94166c3b HTTP/1.1" 500 20231
WARNING 2019-06-20 23:04:28,196 base 152 Not Found: /mobiles/15111411041/count/
WARNING 2019-06-20 23:04:28,199 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 404 2555
WARNING 2019-06-20 23:04:28,202 basehttp 124 "GET /sms_codes/15111411041/?text=xeir&image_code_id=f7447e34-e474-4296-9410-e41a94166c3b HTTP/1.1" 400 46
INFO 2019-06-20 23:04:28,227 basehttp 124 "GET /image_codes/f3e67fad-4102-4484-b3a2-1c711d7aae09/ HTTP/1.1" 200 3246
WARNING 2019-06-20 23:04:39,404 base 152 Not Found: /mobiles/15111411041/count/
WARNING 2019-06-20 23:04:39,407 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 404 2555
WARNING 2019-06-20 23:04:39,410 basehttp 124 "GET /sms_codes/15111411041/?text=f9jo&image_code_id=f3e67fad-4102-4484-b3a2-1c711d7aae09 HTTP/1.1" 400 49
INFO 2019-06-20 23:04:39,437 basehttp 124 "GET /image_codes/e58f2141-837f-4df2-aab5-9cd11cfc132b/ HTTP/1.1" 200 3170
WARNING 2019-06-20 23:05:01,217 base 152 Not Found: /usernames/python1/count/
WARNING 2019-06-20 23:05:01,219 basehttp 124 "GET /usernames/python1/count/ HTTP/1.1" 404 2549
INFO 2019-06-21 11:01:37,149 basehttp 124 "GET /image_codes/03437ea4-e92b-4df0-a3cd-5ae7f815c4fd/ HTTP/1.1" 200 3116
INFO 2019-06-21 11:02:00,691 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:02:12,828 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:02:15,966 basehttp 124 "GET /image_codes/1ddfd556-b5e1-4643-b830-58f1a2389468/ HTTP/1.1" 200 3426
INFO 2019-06-21 11:02:17,398 basehttp 124 "GET /image_codes/b1959fc8-bc87-4871-ba6d-f7c540a26073/ HTTP/1.1" 200 3169
INFO 2019-06-21 11:02:25,382 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:02:25,563 basehttp 124 "GET /sms_codes/15111411041/?text=brjk&image_code_id=b1959fc8-bc87-4871-ba6d-f7c540a26073 HTTP/1.1" 200 16
INFO 2019-06-21 11:03:12,100 basehttp 124 "OPTIONS /users/ HTTP/1.1" 200 0
INFO 2019-06-21 11:03:12,118 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:03:12,120 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:03:12,268 basehttp 124 "POST /users/ HTTP/1.1" 201 232
WARNING 2019-06-21 11:03:41,067 tasks 32 发送验证码短信[失败][ mobile: 15111411041 ]
INFO 2019-06-21 11:03:41,589 basehttp 124 "GET /image_codes/43da1abc-0928-44c0-b3f4-634a92138bf6/ HTTP/1.1" 200 3262
INFO 2019-06-21 11:03:43,157 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:32:50,869 basehttp 124 "GET /mobiles/14311111111/count/ HTTP/1.1" 200 34
INFO 2019-06-21 11:32:54,225 basehttp 124 "GET /image_codes/f6d97dee-a4c2-4fa2-b951-8933166648b3/ HTTP/1.1" 200 3449
INFO 2019-06-21 11:33:02,919 basehttp 124 "GET /sms_codes/14311111111/?text=cnl3&image_code_id=f6d97dee-a4c2-4fa2-b951-8933166648b3 HTTP/1.1" 200 16
INFO 2019-06-21 11:33:02,926 basehttp 124 "GET /mobiles/14311111111/count/ HTTP/1.1" 200 34
WARNING 2019-06-21 11:33:03,228 tasks 32 发送验证码短信[失败][ mobile: 14311111111 ]
WARNING 2019-06-21 14:42:09,245 basehttp 124 "GET /sms_codes/14311111111/?text=cnl3&image_code_id=f6d97dee-a4c2-4fa2-b951-8933166648b3 HTTP/1.1" 400 46
INFO 2019-06-21 14:42:09,259 basehttp 124 "GET /mobiles/14311111111/count/ HTTP/1.1" 200 34
INFO 2019-06-21 14:42:09,311 basehttp 124 "GET /image_codes/331083f1-5d51-4604-b650-b3255ea1ab5b/ HTTP/1.1" 200 3289
WARNING 2019-06-21 14:42:10,662 basehttp 124 "GET /sms_codes/14311111111/?text=cnl3&image_code_id=331083f1-5d51-4604-b650-b3255ea1ab5b HTTP/1.1" 400 46
INFO 2019-06-21 14:42:10,674 basehttp 124 "GET /mobiles/14311111111/count/ HTTP/1.1" 200 34
INFO 2019-06-21 14:42:10,699 basehttp 124 "GET /image_codes/da725d73-86ab-47f2-95c1-e6a631dea473/ HTTP/1.1" 200 3054
INFO 2019-06-21 14:42:12,624 basehttp 124 "GET /image_codes/487e8759-6390-4f8d-846b-b99f5e7967d4/ HTTP/1.1" 200 3010
INFO 2019-06-21 14:42:19,404 basehttp 124 "GET /sms_codes/14311111111/?text=bs8d&image_code_id=487e8759-6390-4f8d-846b-b99f5e7967d4 HTTP/1.1" 200 16
INFO 2019-06-21 14:42:19,415 basehttp 124 "GET /mobiles/14311111111/count/ HTTP/1.1" 200 34
WARNING 2019-06-21 14:42:19,670 tasks 32 发送验证码短信[失败][ mobile: 14311111111 ]
INFO 2019-06-21 21:12:00,054 basehttp 124 "GET /image_codes/a3cbe05c-be66-4a18-911d-9b71fc13060e/ HTTP/1.1" 200 3131
INFO 2019-06-21 21:12:02,911 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-21 21:12:10,059 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-21 21:12:21,329 basehttp 124 "GET /usernames/leondongjie/count/ HTTP/1.1" 200 36
INFO 2019-06-21 21:12:33,371 basehttp 124 "GET /mobiles/15111411041/count/ HTTP/1.1" 200 34
INFO 2019-06-21 21:12:44,487 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-21 21:12:44,571 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 214
INFO 2019-06-21 21:13:24,525 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 214
INFO 2019-06-21 21:18:48,032 basehttp 124 "GET /image_codes/7aaeee21-fd90-4fda-9781-ca3c0e714cc6/ HTTP/1.1" 200 3125
INFO 2019-06-21 21:18:50,647 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-21 21:19:03,062 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-21 21:19:03,216 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 214
INFO 2019-06-21 21:35:51,931 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-21 21:35:52,006 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 214
INFO 2019-06-21 21:50:07,526 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-21 21:50:07,595 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 214
WARNING 2019-06-23 12:29:41,104 base 152 Not Found: /oauth/qq/authorization/
WARNING 2019-06-23 12:29:41,108 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 404 3212
WARNING 2019-06-23 12:29:42,643 base 152 Not Found: /oauth/qq/authorization/
WARNING 2019-06-23 12:29:42,645 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 404 3212
INFO 2019-06-23 12:34:08,534 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2019-06-23 20:39:53,531 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
ERROR 2019-06-23 20:40:27,579 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/views.py", line 45, in get
    access_token = oauth_qq.get_access_token(code)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/utils.py", line 70, in get_access_token
    access_token = resp_dict.get['access_token']
TypeError: 'builtin_function_or_method' object is not subscriptable
ERROR 2019-06-23 20:40:27,634 basehttp 124 "GET /oauth/qq/user/?code=24E3C3505B86387D9D783BF191BDD8E9 HTTP/1.1" 500 17062
ERROR 2019-06-23 20:42:52,496 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/views.py", line 45, in get
    access_token = oauth_qq.get_access_token(code)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/utils.py", line 72, in get_access_token
    return access_token[0]
TypeError: 'NoneType' object is not subscriptable
ERROR 2019-06-23 20:42:52,558 basehttp 124 "GET /oauth/qq/user/?code=24E3C3505B86387D9D783BF191BDD8E9 HTTP/1.1" 500 17000
INFO 2019-06-23 20:45:43,591 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
ERROR 2019-06-23 20:46:38,515 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/views.py", line 46, in get
    openid = oauth_qq.get_openid(access_token)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/utils.py", line 75, in get_openid
    url = 'https://graph.qq.com/oauth2.0/me?access_token=' + access_token
TypeError: must be str, not list
ERROR 2019-06-23 20:46:38,576 basehttp 124 "GET /oauth/qq/user/?code=DB1115385A1CE96DA0238278465FA91D HTTP/1.1" 500 17003
INFO 2019-06-23 20:47:21,667 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2019-06-23 20:47:35,510 basehttp 124 "GET /oauth/qq/user/?code=9D25F12AD2F4C39E0BD32EAEF9BF20EA HTTP/1.1" 200 233
INFO 2019-06-23 20:47:35,685 basehttp 124 "GET /image_codes/1b053069-2601-49d9-bc19-b344e79d097e/ HTTP/1.1" 200 3144
ERROR 2019-06-24 07:42:39,565 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/views.py", line 50, in get
    access_token = oauth_qq.get_access_token(code)
  File "/Users/DZ/Desktop/MEIDUO MALL/meiduo_mall/meiduo_mall/apps/oauth/utils.py", line 72, in get_access_token
    return access_token[0]
TypeError: 'NoneType' object is not subscriptable
ERROR 2019-06-24 07:42:39,642 basehttp 124 "GET /oauth/qq/user/?code=9D25F12AD2F4C39E0BD32EAEF9BF20EA HTTP/1.1" 500 17000
INFO 2019-06-24 07:43:24,413 basehttp 124 "GET /image_codes/6b10f7e5-b3a2-44db-96c7-2b6e91c47462/ HTTP/1.1" 200 3179
INFO 2019-06-24 07:43:28,881 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-24 07:43:30,894 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2019-06-24 07:45:12,027 basehttp 124 "GET /oauth/qq/user/?code=47825BEEE9F1ED72EA22767665E80B34 HTTP/1.1" 200 233
INFO 2019-06-24 07:45:12,076 basehttp 124 "GET /image_codes/be052169-7c12-493c-9a38-f782a5c8c82b/ HTTP/1.1" 200 3380
INFO 2019-06-24 07:45:47,488 basehttp 124 "GET /sms_codes/15111411041/?text=e7oi&image_code_id=be052169-7c12-493c-9a38-f782a5c8c82b HTTP/1.1" 200 16
INFO 2019-06-24 17:27:22,067 basehttp 124 "GET /image_codes/a19dee21-8d5b-4768-869b-c472e70426c3/ HTTP/1.1" 200 3476
INFO 2019-06-24 17:27:25,926 basehttp 124 "GET /usernames/python123/count/ HTTP/1.1" 200 34
INFO 2019-06-27 12:48:56,137 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-27 12:48:56,312 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 214
INFO 2019-06-27 12:49:08,247 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-27 12:49:08,371 basehttp 124 "GET /user/ HTTP/1.1" 200 86
INFO 2019-06-27 12:49:16,702 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2019-06-27 12:49:16,917 basehttp 124 "PUT /email/ HTTP/1.1" 200 44
INFO 2019-06-27 12:53:11,941 basehttp 124 "GET /user/ HTTP/1.1" 200 111
INFO 2019-06-27 12:53:13,755 basehttp 124 "PUT /email/ HTTP/1.1" 200 44
INFO 2019-06-27 13:10:50,951 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-27 13:10:51,355 basehttp 124 "GET /user/ HTTP/1.1" 200 111
INFO 2019-06-27 13:11:00,452 basehttp 124 "GET /user/ HTTP/1.1" 200 111
INFO 2019-06-27 13:11:05,703 basehttp 124 "GET /user/ HTTP/1.1" 200 111
INFO 2019-06-27 13:11:12,851 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2019-06-27 13:13:14,851 basehttp 124 "GET /oauth/qq/user/?code=686F924E607A6B9EC5E0B2A65CFA7E8D HTTP/1.1" 200 233
INFO 2019-06-27 13:13:15,004 basehttp 124 "GET /image_codes/efb262f6-0451-470d-aac8-cc10f21fd535/ HTTP/1.1" 200 3215
INFO 2019-06-27 13:13:39,875 basehttp 124 "GET /sms_codes/15111411041/?text=zko5&image_code_id=efb262f6-0451-470d-aac8-cc10f21fd535 HTTP/1.1" 200 16
INFO 2019-06-27 13:14:36,283 basehttp 124 "OPTIONS /oauth/qq/user/ HTTP/1.1" 200 0
INFO 2019-06-27 13:14:36,370 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 201 265
INFO 2019-06-27 13:14:42,205 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-27 13:14:42,436 basehttp 124 "GET /user/ HTTP/1.1" 200 111
INFO 2019-06-27 13:14:49,199 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2019-06-27 13:14:49,228 basehttp 124 "PUT /email/ HTTP/1.1" 200 44
INFO 2019-06-28 13:19:11,894 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
WARNING 2019-06-28 13:19:12,144 basehttp 124 "GET /user/ HTTP/1.1" 401 35
INFO 2019-06-28 13:19:19,833 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-28 13:19:19,914 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-28 13:19:20,472 basehttp 124 "GET /user/ HTTP/1.1" 200 111
INFO 2019-06-28 13:19:22,303 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2019-06-28 13:19:22,545 basehttp 124 "PUT /email/ HTTP/1.1" 200 44
WARNING 2019-06-28 13:19:29,171 tasks 32 发送验证码短信[失败][ mobile: 15111411041 ]
INFO 2019-06-28 13:20:02,260 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU2MTY5OTE2MiwiZXhwIjoxNTYxNzg1NTYyfQ.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6Indhbmdkb25namllMTk5NEBnbWFpbC5jb20ifQ.1alj0CaWcTbLgyPOaQ-qaIibRVHmC8MTp2_U3dN3MAxsM2_4A1_uz5yfpGMmy-j0dpRWq7xw-1CPXXa8DAYaxA HTTP/1.1" 200 16
INFO 2019-06-28 14:49:20,711 basehttp 124 "GET /image_codes/11/ HTTP/1.1" 200 3339
WARNING 2019-06-28 14:49:21,491 base 152 Not Found: /favicon.ico
WARNING 2019-06-28 14:49:21,496 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 3646
WARNING 2019-06-28 14:49:27,532 base 152 Not Found: /
WARNING 2019-06-28 14:49:27,532 basehttp 124 "GET / HTTP/1.1" 404 3595
WARNING 2019-06-28 14:51:25,521 base 152 Not Found: /oauth
WARNING 2019-06-28 14:51:25,523 basehttp 124 "GET /oauth HTTP/1.1" 404 3628
INFO 2019-06-28 14:51:37,525 basehttp 124 "GET /admin HTTP/1.1" 301 0
INFO 2019-06-28 14:51:37,560 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-06-28 14:51:37,713 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
INFO 2019-06-28 14:51:37,848 basehttp 124 "GET /static/admin/css/login.css HTTP/1.1" 200 1203
INFO 2019-06-28 14:51:37,852 basehttp 124 "GET /static/admin/css/base.css HTTP/1.1" 200 16066
INFO 2019-06-28 14:51:37,960 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2019-06-28 14:51:38,628 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
INFO 2019-06-28 14:51:38,629 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO 2019-06-28 14:51:48,225 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1784
INFO 2019-06-28 14:51:48,527 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2019-06-28 14:53:14,112 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1784
INFO 2019-06-28 15:07:50,499 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1783
INFO 2019-06-28 15:07:59,003 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1783
INFO 2019-06-28 15:08:14,708 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1804
INFO 2019-06-28 15:08:21,607 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1804
INFO 2019-06-28 19:38:39,518 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-06-28 19:38:39,623 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
INFO 2019-06-28 19:38:49,727 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2019-06-28 19:38:49,828 basehttp 124 "GET /admin/ HTTP/1.1" 200 2352
INFO 2019-06-28 19:38:49,940 basehttp 124 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO 2019-06-28 19:38:49,968 basehttp 124 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2019-06-28 19:38:49,972 basehttp 124 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-06-28 19:39:03,164 basehttp 124 "GET /admin/auth/group/ HTTP/1.1" 200 3357
INFO 2019-06-28 19:39:03,296 basehttp 124 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
INFO 2019-06-28 19:39:03,331 basehttp 124 "GET /static/admin/js/core.js HTTP/1.1" 200 7976
INFO 2019-06-28 19:39:03,346 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2019-06-28 19:39:03,349 basehttp 124 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
INFO 2019-06-28 19:39:03,358 basehttp 124 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6591
INFO 2019-06-28 19:39:03,358 basehttp 124 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
INFO 2019-06-28 19:39:03,439 basehttp 124 "GET /static/admin/js/actions.js HTTP/1.1" 200 6501
INFO 2019-06-28 19:39:03,441 basehttp 124 "GET /static/admin/js/urlify.js HTTP/1.1" 200 8186
INFO 2019-06-28 19:39:03,443 basehttp 124 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2019-06-28 19:39:03,443 basehttp 124 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
INFO 2019-06-28 19:39:03,449 basehttp 124 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
INFO 2019-06-28 19:39:03,583 basehttp 124 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2019-06-28 19:39:05,950 basehttp 124 "GET /admin/ HTTP/1.1" 200 2352
INFO 2019-06-28 19:39:09,261 basehttp 124 "GET /admin/auth/ HTTP/1.1" 200 2229
INFO 2019-06-28 19:39:11,235 basehttp 124 "GET /admin/ HTTP/1.1" 200 2352
WARNING 2019-06-28 19:39:14,172 base 152 Not Found: /
WARNING 2019-06-28 19:39:14,173 basehttp 124 "GET / HTTP/1.1" 404 3595
INFO 2019-06-28 19:39:18,342 basehttp 124 "GET /admin/ HTTP/1.1" 200 2352
INFO 2019-06-28 21:08:19,131 basehttp 124 "GET /admin/ HTTP/1.1" 200 7506
INFO 2019-06-28 21:12:30,886 basehttp 124 "GET /admin/goods/goods/ HTTP/1.1" 200 3039
INFO 2019-06-28 21:12:31,129 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2019-06-28 21:13:11,004 basehttp 124 "GET /admin/goods/goods/add/ HTTP/1.1" 200 15619
INFO 2019-06-28 21:13:11,246 basehttp 124 "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
INFO 2019-06-28 21:13:11,251 basehttp 124 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2019-06-28 21:13:11,254 basehttp 124 "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2019-06-28 21:13:11,254 basehttp 124 "GET /static/ckeditor/ckeditor-init.js HTTP/1.1" 200 2216
INFO 2019-06-28 21:13:11,263 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2019-06-28 21:13:11,281 basehttp 124 "GET /static/ckeditor/ckeditor/ckeditor.js HTTP/1.1" 200 701922
INFO 2019-06-28 21:13:11,312 basehttp 124 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
INFO 2019-06-28 21:13:11,313 basehttp 124 "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO 2019-06-28 21:13:11,901 basehttp 124 "GET /static/ckeditor/ckeditor/config.js?t=J39A HTTP/1.1" 200 338
INFO 2019-06-28 21:13:12,029 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/editor.css?t=J39A HTTP/1.1" 200 47805
INFO 2019-06-28 21:13:12,033 basehttp 124 "GET /static/ckeditor/ckeditor/lang/zh-cn.js?t=J39A HTTP/1.1" 200 18573
INFO 2019-06-28 21:13:12,662 basehttp 124 "GET /static/ckeditor/ckeditor/styles.js?t=J39A HTTP/1.1" 200 5579
INFO 2019-06-28 21:13:12,741 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css?t=J39A HTTP/1.1" 200 381
INFO 2019-06-28 21:13:12,742 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/copyformatting/styles/copyformatting.css HTTP/1.1" 200 1513
INFO 2019-06-28 21:13:12,743 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/wsc/skins/moono-lisa/wsc.css?t=J39A HTTP/1.1" 200 1306
INFO 2019-06-28 21:13:12,743 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/scayt/dialogs/dialog.css?t=J39A HTTP/1.1" 200 419
INFO 2019-06-28 21:13:12,744 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/tableselection/styles/tableselection.css HTTP/1.1" 200 1145
INFO 2019-06-28 21:13:12,846 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/icons.png?t=e1836357e HTTP/1.1" 200 12421
INFO 2019-06-28 21:13:13,140 basehttp 124 "GET /static/ckeditor/ckeditor/contents.css?t=J39A HTTP/1.1" 200 3094
INFO 2019-06-28 21:17:53,586 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/dialog.css?t=J39A HTTP/1.1" 200 13708
INFO 2019-06-28 21:17:53,587 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/image/dialogs/image.js?t=J39A HTTP/1.1" 200 21360
INFO 2019-06-28 21:17:53,703 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/images/close.png HTTP/1.1" 200 615
INFO 2019-06-28 21:17:53,718 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/images/lock.png HTTP/1.1" 200 506
INFO 2019-06-28 21:17:53,722 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/images/refresh.png HTTP/1.1" 200 757
INFO 2019-06-28 21:18:48,707 basehttp 124 "POST /ckeditor/upload/ HTTP/1.1" 200 159
INFO 2019-06-28 21:18:48,831 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/image/images/noimage.png?t=J39A HTTP/1.1" 200 1610
INFO 2019-06-28 21:18:48,831 basehttp 124 "GET /static/ckeditor/ckeditor/skins/moono-lisa/images/lock-open.png HTTP/1.1" 200 511
INFO 2019-06-28 21:24:30,397 basehttp 124 "POST /ckeditor/upload/ HTTP/1.1" 200 159
INFO 2019-06-28 21:24:30,445 basehttp 124 "GET /static/ckeditor/ckeditor/plugins/image/images/noimage.png?t=J39A HTTP/1.1" 304 0
INFO 2019-06-29 11:33:33,666 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2019-06-29 11:33:39,269 basehttp 124 "GET /areas/110000/ HTTP/1.1" 200 74
INFO 2019-06-29 11:33:42,831 basehttp 124 "GET /areas/110100/ HTTP/1.1" 200 575
INFO 2019-06-29 11:33:51,621 basehttp 124 "GET /areas/420000/ HTTP/1.1" 200 542
INFO 2019-06-29 11:33:57,592 basehttp 124 "GET /areas/429000/ HTTP/1.1" 200 197
INFO 2019-06-30 14:11:32,419 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 14:11:32,530 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 14:23:39,865 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 14:23:39,936 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 14:31:37,010 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 14:31:45,166 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-30 14:31:45,278 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-06-30 14:31:50,225 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2019-06-30 14:31:50,279 basehttp 124 "GET /addresses/ HTTP/1.1" 200 65
INFO 2019-06-30 15:43:02,889 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 15:43:02,973 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 15:43:30,150 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2019-06-30 15:43:30,205 basehttp 124 "GET /addresses/ HTTP/1.1" 200 65
INFO 2019-06-30 15:48:37,317 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 15:48:37,381 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 15:51:13,379 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 16:41:42,971 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 16:41:43,066 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 16:42:16,571 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 16:42:36,556 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-30 16:42:36,703 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-06-30 17:00:23,421 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 17:00:23,507 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 17:09:25,429 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-30 17:09:25,595 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-06-30 18:11:16,579 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 18:11:16,662 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 18:11:22,115 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 21:52:43,390 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-06-30 21:52:43,519 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-06-30 21:55:54,104 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-06-30 21:55:54,399 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-06-30 21:55:54,644 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
ERROR 2019-06-30 21:55:55,635 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 203, in get
    serializer = serializers.SKUserializer(skus,many = True)
AttributeError: module 'users.serializers' has no attribute 'SKUserializer'
ERROR 2019-06-30 21:55:55,722 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 18314
INFO 2019-06-30 21:56:13,208 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-06-30 21:56:13,357 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 203, in get
    serializer = serializers.SKUserializer(skus,many = True)
AttributeError: module 'users.serializers' has no attribute 'SKUserializer'
ERROR 2019-06-30 21:56:13,451 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 18314
INFO 2019-06-30 21:58:39,313 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-06-30 21:58:39,419 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 09:03:50,700 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-01 09:03:50,820 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 09:03:51,115 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-01 09:03:51,154 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 09:55:13,896 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-01 09:55:14,042 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 09:55:14,155 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-01 09:55:14,191 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 09:56:31,423 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-01 09:56:31,557 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 09:56:31,686 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-01 09:56:31,723 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 10:02:51,844 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 10:02:52,061 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 10:02:59,931 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-01 10:03:00,108 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 10:03:00,173 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-01 10:03:00,256 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 14:13:34,469 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-01 14:13:34,654 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 14:13:34,887 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-01 14:13:34,963 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 19:25:35,126 basehttp 124 "GET /admin/ HTTP/1.1" 200 7506
INFO 2019-07-01 19:25:35,183 basehttp 124 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2019-07-01 19:25:35,188 basehttp 124 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2019-07-01 19:25:35,309 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2019-07-01 19:25:35,455 basehttp 124 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2019-07-01 19:25:35,459 basehttp 124 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2019-07-01 19:25:36,133 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2019-07-01 19:25:36,137 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2019-07-01 19:25:36,139 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
WARNING 2019-07-01 19:25:58,451 base 152 Not Found: /admin/categories/115/skus
WARNING 2019-07-01 19:25:58,461 basehttp 124 "GET /admin/categories/115/skus HTTP/1.1" 404 10942
INFO 2019-07-01 19:26:21,695 basehttp 124 "GET /categories/115/skus HTTP/1.1" 301 0
INFO 2019-07-01 19:26:22,013 basehttp 124 "GET /categories/115/skus/ HTTP/1.1" 200 9429
INFO 2019-07-01 19:26:22,163 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2019-07-01 19:26:22,193 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
INFO 2019-07-01 19:26:22,194 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2019-07-01 19:26:22,195 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2019-07-01 19:26:22,217 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2019-07-01 19:26:22,221 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
INFO 2019-07-01 19:26:22,387 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2019-07-01 19:26:22,419 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
INFO 2019-07-01 19:26:22,431 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2019-07-01 19:26:22,443 basehttp 124 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2019-07-01 19:26:22,444 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2019-07-01 19:26:22,606 basehttp 124 "GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028
WARNING 2019-07-01 19:31:08,875 base 152 Not Found: /categories/115/
INFO 2019-07-01 19:31:08,879 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-01 19:31:08,896 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-01 19:31:08,898 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 7392
WARNING 2019-07-01 19:31:08,899 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 7416
INFO 2019-07-01 19:31:08,923 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2019-07-01 19:31:09,641 base 152 Not Found: /cart/
WARNING 2019-07-01 19:31:09,642 basehttp 124 "GET /cart/ HTTP/1.1" 404 7362
INFO 2019-07-01 19:32:52,440 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-07-01 19:32:52,524 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-07-01 19:34:57,029 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-01 19:34:57,230 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 19:34:58,036 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-01 19:34:58,232 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
INFO 2019-07-01 19:35:10,996 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-01 19:35:11,187 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 2
WARNING 2019-07-01 19:35:23,518 base 152 Not Found: /categories/115/
INFO 2019-07-01 19:35:23,519 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2019-07-01 19:35:23,521 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 7392
INFO 2019-07-01 19:35:23,607 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-01 19:35:23,621 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-01 19:35:23,622 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 7416
WARNING 2019-07-01 19:35:23,872 base 152 Not Found: /cart/
WARNING 2019-07-01 19:35:23,873 basehttp 124 "GET /cart/ HTTP/1.1" 404 7362
INFO 2019-07-01 19:36:27,640 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-07-01 19:37:53,517 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-07-01 19:38:41,162 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
INFO 2019-07-01 19:38:48,375 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
WARNING 2019-07-01 19:39:00,335 base 152 Not Found: /categories/157/
WARNING 2019-07-01 19:39:00,363 base 152 Not Found: /categories/157/hotskus/
WARNING 2019-07-01 19:39:00,366 base 152 Not Found: /cart/
WARNING 2019-07-01 19:39:00,367 basehttp 124 "GET /categories/157/ HTTP/1.1" 404 7392
WARNING 2019-07-01 19:39:00,380 basehttp 124 "GET /categories/157/hotskus/ HTTP/1.1" 404 7416
WARNING 2019-07-01 19:39:00,381 basehttp 124 "GET /cart/ HTTP/1.1" 404 7362
INFO 2019-07-01 19:39:00,384 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 452
INFO 2019-07-01 21:55:04,930 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-01 21:55:04,986 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-01 21:55:04,990 base 152 Not Found: /categories/115/
WARNING 2019-07-01 21:55:05,009 base 152 Not Found: /cart/
WARNING 2019-07-01 21:55:05,012 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 7416
WARNING 2019-07-01 21:55:05,013 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 7392
WARNING 2019-07-01 21:55:05,014 basehttp 124 "GET /cart/ HTTP/1.1" 404 7362
INFO 2019-07-01 21:55:05,054 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2019-07-01 23:09:53,736 basehttp 124 "GET /skus/search/?text%20=%20%27%E5%8D%8E%27 HTTP/1.1" 200 8475
INFO 2019-07-01 23:09:53,962 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2019-07-01 23:09:53,967 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2019-07-01 23:09:53,970 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
INFO 2019-07-01 23:09:53,971 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2019-07-01 23:09:53,975 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
INFO 2019-07-01 23:09:53,979 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2019-07-01 23:09:53,999 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2019-07-01 23:09:54,022 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2019-07-01 23:09:54,023 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2019-07-01 23:09:54,026 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
INFO 2019-07-01 23:09:54,045 basehttp 124 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2019-07-01 23:17:18,550 basehttp 124 "GET /skus/search/?text=%E5%8D%8E&page=1&page_size=6 HTTP/1.1" 200 2602
INFO 2019-07-01 23:17:28,106 basehttp 124 "GET /skus/search/?text=%E5%8D%8E&page=2&page_size=6 HTTP/1.1" 200 1791
INFO 2019-07-01 23:17:29,791 basehttp 124 "GET /skus/search/?text=%E5%8D%8E&page=1&page_size=6 HTTP/1.1" 200 2602
INFO 2019-07-03 11:13:00,359 basehttp 124 "GET /skus/search/?text=%E5%8D%8E&page=1&page_size=6 HTTP/1.1" 200 2602
INFO 2019-07-03 11:13:06,188 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2019-07-03 11:13:06,299 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 247
WARNING 2019-07-03 11:13:11,953 base 152 Not Found: /categories/115/
WARNING 2019-07-03 11:13:11,967 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 8605
INFO 2019-07-03 11:13:11,968 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-03 11:13:11,977 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-03 11:13:11,980 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 8629
INFO 2019-07-03 11:13:12,023 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2019-07-03 11:13:12,067 base 152 Not Found: /cart/
WARNING 2019-07-03 11:13:12,067 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 11:13:13,681 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-03 11:13:13,972 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 11:13:24,706 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 11:13:24,833 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 11:13:24,976 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 200, in get
    sku = SKU.objects.get(id= sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 11:13:25,101 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20789
INFO 2019-07-03 11:13:27,539 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 11:13:27,677 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 200, in get
    sku = SKU.objects.get(id= sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 11:13:27,758 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20789
WARNING 2019-07-03 11:13:41,353 base 152 Not Found: /cart/
WARNING 2019-07-03 11:13:41,366 base 152 Not Found: /categories/157/
WARNING 2019-07-03 11:13:41,372 base 152 Not Found: /categories/157/hotskus/
WARNING 2019-07-03 11:13:41,373 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
WARNING 2019-07-03 11:13:41,376 basehttp 124 "GET /categories/157/ HTTP/1.1" 404 8605
WARNING 2019-07-03 11:13:41,376 basehttp 124 "GET /categories/157/hotskus/ HTTP/1.1" 404 8629
INFO 2019-07-03 11:13:41,388 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 452
INFO 2019-07-03 11:13:43,199 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 11:13:54,883 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 11:13:54,964 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 200, in get
    sku = SKU.objects.get(id= sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 11:13:55,220 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20789
INFO 2019-07-03 11:14:18,339 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 11:14:18,479 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 200, in get
    sku = SKU.objects.get(id= sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 11:14:18,563 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20789
INFO 2019-07-03 12:37:48,769 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 12:37:48,990 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 12:37:49,560 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
ERROR 2019-07-03 12:37:49,647 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 200, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 12:37:49,808 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
WARNING 2019-07-03 12:38:36,461 base 152 Not Found: /categories/115/
INFO 2019-07-03 12:38:36,470 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-03 12:38:36,482 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-03 12:38:36,488 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 8629
WARNING 2019-07-03 12:38:36,489 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 8605
INFO 2019-07-03 12:38:36,508 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2019-07-03 12:38:36,715 base 152 Not Found: /cart/
WARNING 2019-07-03 12:38:36,716 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 12:38:42,550 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-03 12:38:42,697 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 12:39:15,556 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 12:39:15,766 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 12:39:15,866 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 200, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 12:39:15,966 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
INFO 2019-07-03 12:46:53,478 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 12:46:53,613 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 12:46:53,839 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
INFO 2019-07-03 15:26:55,439 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 15:26:55,637 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 15:26:56,213 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
ERROR 2019-07-03 15:26:56,275 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 196, in get
    sku_id_list = int(sku_id_list.decode())
AttributeError: 'list' object has no attribute 'decode'
ERROR 2019-07-03 15:26:56,382 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 18888
INFO 2019-07-03 15:29:01,756 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 15:29:02,226 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 196, in get
    sku_id_list = int(sku_id_list)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
ERROR 2019-07-03 15:29:02,313 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 18943
WARNING 2019-07-03 15:29:15,477 base 152 Not Found: /categories/157/
WARNING 2019-07-03 15:29:15,482 basehttp 124 "GET /categories/157/ HTTP/1.1" 404 8605
INFO 2019-07-03 15:29:15,499 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 452
WARNING 2019-07-03 15:29:15,526 base 152 Not Found: /categories/157/hotskus/
INFO 2019-07-03 15:29:15,527 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-03 15:29:15,528 basehttp 124 "GET /categories/157/hotskus/ HTTP/1.1" 404 8629
WARNING 2019-07-03 15:29:15,700 base 152 Not Found: /cart/
WARNING 2019-07-03 15:29:15,701 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 15:29:19,521 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 15:29:29,157 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 15:29:29,266 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 196, in get
    sku_id_list = int(sku_id_list)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
ERROR 2019-07-03 15:29:29,320 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 18943
INFO 2019-07-03 18:59:57,936 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 18:59:58,042 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 18:59:58,443 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
ERROR 2019-07-03 18:59:58,512 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 18:59:58,819 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
INFO 2019-07-03 19:01:29,106 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 19:01:29,220 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 19:01:29,396 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
WARNING 2019-07-03 19:01:35,779 base 152 Not Found: /categories/157/
INFO 2019-07-03 19:01:35,780 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-03 19:01:35,800 base 152 Not Found: /categories/157/hotskus/
WARNING 2019-07-03 19:01:35,801 basehttp 124 "GET /categories/157/ HTTP/1.1" 404 8605
WARNING 2019-07-03 19:01:35,809 basehttp 124 "GET /categories/157/hotskus/ HTTP/1.1" 404 8629
INFO 2019-07-03 19:01:35,821 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 452
WARNING 2019-07-03 19:01:36,066 base 152 Not Found: /cart/
WARNING 2019-07-03 19:01:36,067 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 19:01:37,815 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 19:01:41,381 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 19:01:41,466 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 19:01:41,539 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
WARNING 2019-07-03 19:09:54,366 base 152 Not Found: /cart/
WARNING 2019-07-03 19:09:54,395 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-03 19:09:54,356 base 152 Not Found: /categories/115/
WARNING 2019-07-03 19:09:54,405 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
WARNING 2019-07-03 19:09:54,413 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 8605
WARNING 2019-07-03 19:09:54,429 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 8629
INFO 2019-07-03 19:09:54,732 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2019-07-03 19:13:25,294 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 19:13:36,057 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-03 19:15:38,506 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 15
INFO 2019-07-03 19:18:22,782 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 19:18:23,076 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 19:18:23,189 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 19:18:23,384 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
INFO 2019-07-03 19:18:35,094 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 19:18:35,262 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 19:18:35,390 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
INFO 2019-07-03 19:18:36,407 basehttp 124 "GET /user/ HTTP/1.1" 200 110
ERROR 2019-07-03 19:18:36,524 exception 135 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/DZ/Desktop/MEIDUOMALL/meiduo_mall/meiduo_mall/apps/users/views.py", line 201, in get
    sku = SKU.objects.get(id = sku_id)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/Users/DZ/leonVEnv/meiduo_mall/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: b'None'
ERROR 2019-07-03 19:18:36,604 basehttp 124 "GET /browse_histories/ HTTP/1.1" 500 20790
INFO 2019-07-03 19:20:39,829 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 19:20:39,927 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 4
INFO 2019-07-03 19:22:29,189 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2019-07-03 19:22:29,433 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-03 19:22:29,457 base 152 Not Found: /categories/115/
WARNING 2019-07-03 19:22:29,466 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 8629
WARNING 2019-07-03 19:22:29,478 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 8605
INFO 2019-07-03 19:22:29,562 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2019-07-03 19:22:29,849 base 152 Not Found: /cart/
WARNING 2019-07-03 19:22:29,867 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 19:25:33,918 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-03 19:26:30,722 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2019-07-03 19:28:40,846 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 19:28:41,085 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 19:28:41,337 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 4
INFO 2019-07-03 19:28:45,494 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 19:28:45,743 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 4
WARNING 2019-07-03 19:28:59,510 base 152 Not Found: /cart/
WARNING 2019-07-03 19:28:59,540 base 152 Not Found: /categories/119/
WARNING 2019-07-03 19:28:59,574 base 152 Not Found: /categories/119/hotskus/
WARNING 2019-07-03 19:28:59,578 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
WARNING 2019-07-03 19:28:59,587 basehttp 124 "GET /categories/119/hotskus/ HTTP/1.1" 404 8629
WARNING 2019-07-03 19:28:59,602 basehttp 124 "GET /categories/119/ HTTP/1.1" 404 8605
INFO 2019-07-03 19:28:59,627 basehttp 124 "GET /categories/119/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2019-07-03 19:29:07,708 base 152 Not Found: /categories/157/
WARNING 2019-07-03 19:29:07,737 base 152 Not Found: /cart/
WARNING 2019-07-03 19:29:07,765 basehttp 124 "GET /categories/157/ HTTP/1.1" 404 8605
WARNING 2019-07-03 19:29:07,804 base 152 Not Found: /categories/157/hotskus/
WARNING 2019-07-03 19:29:07,806 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 19:29:07,809 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 452
WARNING 2019-07-03 19:29:07,823 basehttp 124 "GET /categories/157/hotskus/ HTTP/1.1" 404 8629
INFO 2019-07-03 19:29:10,015 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 12
INFO 2019-07-03 19:29:16,330 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 19:29:16,482 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 4
INFO 2019-07-03 20:07:05,070 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2019-07-03 20:07:05,485 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 20:07:05,562 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
INFO 2019-07-03 20:07:05,617 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 440
WARNING 2019-07-03 20:07:24,824 base 152 Not Found: /categories/115/
WARNING 2019-07-03 20:07:24,828 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 8605
INFO 2019-07-03 20:07:24,843 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
INFO 2019-07-03 20:07:24,871 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2019-07-03 20:07:24,920 base 152 Not Found: /categories/115/hotskus/
WARNING 2019-07-03 20:07:24,920 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 8629
WARNING 2019-07-03 20:07:24,977 base 152 Not Found: /cart/
WARNING 2019-07-03 20:07:24,978 basehttp 124 "GET /cart/ HTTP/1.1" 404 8575
INFO 2019-07-03 20:07:27,244 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
INFO 2019-07-03 20:07:32,274 basehttp 124 "GET /user/ HTTP/1.1" 200 110
INFO 2019-07-03 20:07:32,361 basehttp 124 "GET /browse_histories/ HTTP/1.1" 200 440
INFO 2019-07-03 20:07:44,483 basehttp 124 "POST /browse_histories/ HTTP/1.1" 201 13
